### ISSUE TITLE
[에러] 메인화면에서 설정 버튼 클릭/뒤로가기 반복 시 앱 크래시

### ISSUE THREAD

**Issue by hidaehyunlee** [nbcamp/anki-clone-app#7]
<img width="1828" alt="image" src="https://github.com/nbcamp/anki-clone-app/assets/37580034/548ed5e9-0c3d-4b20-a53a-2d6395c69661">

### 시나리오
1. 메인화면에서 설정버튼 클릭
2. 설정화면에서 뒤로가기버튼 클릭
3. 3~4회 정도 반복

에러 메세지와 디버그창 메세지는 스크린샷으로 첨부했습니다.

**Comment by jinyongp** [comment]
a6e8163ba4753b099d42120f6820f856a10ccb96 에서 해결 완료했습니다.
